# Generated by Django 6.0.2 on 2026-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_serviceimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/images/"
            ),
        ),
    ]
