# Generated by Django 6.0.2 on 2026-03-03 14:09

import cloudinary.models
from django.db import migrations, models


def copy_image_to_image_url(apps, schema_editor):
    """Copy existing image URLs to image_url field"""
    ServiceImage = apps.get_model('services', 'ServiceImage')
    for img in ServiceImage.objects.all():
        if img.image:
            img.image_url = str(img.image)
            img.save(update_fields=['image_url'])


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_serviceimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceimage",
            name="image_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(copy_image_to_image_url, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="serviceimage",
            name="image",
        ),
    ]
